import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = { 
  title: {
    absolute:"", // if you want to ignore parent segment (template) 
    default:"Next.js Learning ", //useful for giving a fallback title for child segments
    template:"%s | Next js", //to create dynamic titles by adding a prefix or suffix //property applies to child route segment and not segment in which it is defined
  },//whenever need we can import metadata in the page.tsx and change title: 
  // export const metadata: Metadata = {title: "Anything"};
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header style={{ padding: "1rem", backgroundColor: "lavender" }}>
        <p>Header</p>
        </header>
        {children}
        <footer style={{ padding: "1rem", backgroundColor: "lightblue" }}>
        <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
